### ISSUE TITLE
Code Release Timeline

### ISSUE THREAD

**Issue by mvp18** [vuer-ai/feature-splatting#1]
Hi,

Could you please give an estimate of when the code will be released? Your method has some cool applications which we would like to use for our research. Thanks

**Comment by RogerQi** [comment]
Hello,

Thank you for your interest (sorry I missed this GitHub issue somehow...)! I have just updated the repo with a version in NerfStudio, which has the feature distillation and the basic editing part.

The full version (which is written based on the original INRIA codebase) will be out some time in the next week. I wanted to make the feature implementation publicly available first because I did get many email inquiries specifically asking for the feature part.

**Comment by mvp18** [comment]
Hi,

Thank you so much for getting back. Looking forward to the release of the full version next week!
